name: build

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential qttools5-dev-tools qt6-base-dev libgl1-mesa-dev
    - name: qmake
      run: qmake6
    - name: make
      run: make

  mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: install-qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
    - name: qmake
      run: qmake
    - name: make
      run: make

  wasm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libclang-dev cmake ninja-build
    - name: compile-qt-web
      run: cd tools && ./compile-qt-web
    - name: compile-xaos-web
      run: cd tools && ./compile-xaos-web
